fix: Write an OpenAI-compatible error when context overflows
getappmap/vscode-appland pull request #1031
Opened 2024-10-03 19:00 UTC by dustinbyrne

Previously the server would report an error stating `Message exceeds token limit.`.

This error is now transformed into an OpenAI API compatible error, mimicking the same error returned by the official OpenAI API. This change allows Navie to properly reduce the token count before trying again.

2024-10-04 20:15 UTC, apotterri requested changes
There are a couple of cases where the value of `stream` doesn't seem like it matches the example description.

2024-10-04 20:15 UTC, apotterri commented on test/unit/services/chatCompletion.test.ts
> +        stream: true,
`stream` shouldn't be here, should it? The example says, "when not streaming".

2024-10-04 20:15 UTC, apotterri commented on test/unit/services/chatCompletion.test.ts
> +      const response = await postAuthorized(chatCompletion.url, { model: 'test-model', messages });
And this one seems like it needs `stream: true`?

2024-10-04 20:53 UTC, dustinbyrne commented on test/unit/services/chatCompletion.test.ts
> +      const response = await postAuthorized(chatCompletion.url, { model: 'test-model', messages });
Yeah, it looks like I had named the test cases backwards. This is fixed now :+1:

2024-10-04 20:54 UTC, apotterri approved these changes

2024-10-06 09:26 UTC, dividedmind approved these changes

2024-10-07 13:27 UTC, merged

2024-10-07 19:34 UTC, appland-release commented
:tada: This PR is included in version 0.130.0 :tada:

The release is available on:
- `v0.130.0`
- `v0.130.0`
- [GitHub release](https://github.com/getappmap/vscode-appland/releases/tag/v0.130.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: