feat: add command to install appmap agent
getappmap/vscode-appland pull request #467
Opened 2022-09-20 20:55 UTC by ahtrotta

Fixes applandinc/board#161

2022-09-28 21:49 UTC, dustinbyrne requested changes

2022-09-29 00:06 UTC, ahtrotta commented on src/extension.ts
> +    await processService.install();
I was thinking that if we didn't block the rest of the initialization logic, then the user might try to press the automated install button before the `installAgent` command gets created and then it would fail. Do you think that's a problem?

2022-10-06 13:29 UTC, dustinbyrne approved these changes

2022-10-06 13:29 UTC, merged

2022-10-06 13:42 UTC, appland-release commented
:tada: This PR is included in version 0.45.0 :tada:

The release is available on:
- `v0.45.0`
- [GitHub release](https://github.com/getappmap/vscode-appland/releases/tag/v0.45.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: