fix: Finding counts in the instructions view is consistent
getappmap/vscode-appland pull request #488
Opened 2022-10-18 19:21 UTC by dividedmind

Fixes #485

2022-10-18 20:42 UTC, ahtrotta approved these changes
This looks good to me. I'm surprised that `this.findingsByWorkspace.get(workspaceFolder)` yields an array with duplicate findings, though. Maybe we should open an issue for that?

2022-10-19 18:18 UTC, dustinbyrne requested changes
This change should be rebased with master.

The `findingsByWorkspace` map was removed because it was problematic. Instead the findings are now retrieved dynamically by looking at the source URI in `findingsBySourceUri`.

2022-10-20 00:56 UTC, dividedmind commented
> This change should be rebased with master.
> 
> The `findingsByWorkspace` map was removed because it was problematic. Instead the findings are now retrieved dynamically by looking at the source URI in `findingsBySourceUri`.

Will do, thanks!

2022-10-24 20:28 UTC, dustinbyrne approved these changes

2022-10-24 20:29 UTC, merged

2022-10-24 20:41 UTC, appland-release commented
:tada: This PR is included in version 0.48.4 :tada:

The release is available on:
- `v0.48.4`
- [GitHub release](https://github.com/getappmap/vscode-appland/releases/tag/v0.48.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: