fix: Strip paths of any extra leading path separators
getappmap/vscode-appland pull request #501
Opened 2022-10-27 22:28 UTC by dustinbyrne

I'm not sure how this is possible, but some user's report an error similar to:
```
RangeError: path should be a `path.relative()`d string, but got "/yarn.lock"
```

This occurs regardless of the OS, sometimes using Windows path separators (e.g. `\yarn.lock`).

These paths must have double separators? I'm not sure how it's occurring, but this should fix it.

2022-10-28 09:31 UTC, dividedmind requested changes
I'd really like to see a unit test here.

2022-10-28 17:33 UTC, dustinbyrne commented
Added. Any ideas on how this issue might occur given the line of code that was changed?

2022-10-28 21:12 UTC, merged

2022-10-28 21:25 UTC, appland-release commented
:tada: This PR is included in version 0.48.7 :tada:

The release is available on:
- `v0.48.7`
- [GitHub release](https://github.com/getappmap/vscode-appland/releases/tag/v0.48.7)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-10-31 04:17 UTC, dividedmind commented
> Added. 

Thanks, although I don't see any `//path` patterns in the test?

> Any ideas on how this issue might occur given the line of code that was changed?

My guess would be that a tool or a template adds `//yarn.lock` to gitignore.