Update VS Code for Runtime Analysis Findings Pages
getappmap/vscode-appland pull request #519
Opened 2022-11-10 22:52 UTC by ahtrotta

2022-11-30 18:38 UTC, dustinbyrne requested changes

2022-11-30 18:38 UTC, dustinbyrne commented on src/services/findingsIndex.ts
> +  findingsByHashV2(hash: string): ResolvedFinding[] {
Nit-pick, but I think this should just be `findingsByHash` - The fact that it's `V2` is just an implementation detail that may change in the future.

2022-11-30 18:38 UTC, dustinbyrne commented on src/services/findingsIndex.ts
> +    );
You can destructure the parameter here to cut down on verbosity (`finding.finding`). This isn't really an issue though, just an FYI.
```ts
filter(({ finding }) => finding.ruleTitle === ruleTitle)
```

2022-11-30 18:38 UTC, dustinbyrne commented on src/tree/findingsTreeDataProvider.ts
> +        }
Might be worth a case normalization here but I recognize the type is defined as `'Security' | 'Performance' | 'Maintainability' | 'Stability'`. :shrug:

2022-11-30 18:38 UTC, dustinbyrne commented on src/webviews/findingInfoWebview.ts
> +  const content = fs.readFileSync(docPath, 'utf-8').replace(/\r\n/g, '\n');
The production build is bundled down to a single file, so this path won't exist. Instead of `fs.readFileSync`, this will need to be a dynamic import.

2022-11-30 18:38 UTC, dustinbyrne commented on src/webviews/findingInfoWebview.ts
> +  const content = fs.readFileSync(docPath, 'utf-8').replace(/\r\n/g, '\n');
We'll need another custom type defined in `types/custom.d.ts` as well as a webpack loader rule for `.md` files. This may (?) break our tests as they use `tsc` compiled JavaScript (not webpack) but we'll cross that bridge when we come to it.

2022-12-01 18:48 UTC, ahtrotta commented on src/webviews/findingInfoWebview.ts
> +  const content = fs.readFileSync(docPath, 'utf-8').replace(/\r\n/g, '\n');
No worries, I just changed it so that the rule information is now retrieved from parsing `appmap-findings.json` instead of looking for the markdown file.

2022-12-01 18:50 UTC, ahtrotta commented on src/services/findingsIndex.ts
> +  findingsByHashV2(hash: string): ResolvedFinding[] {
No problem, I renamed it :+1:

2022-12-01 18:52 UTC, ahtrotta commented on src/services/findingsIndex.ts
> +    );
Yeah, good point. I just changed it in a couple of places in this file.

2022-12-05 17:24 UTC, dustinbyrne commented on src/webviews/findingInfoWebview.ts
> +  const content = fs.readFileSync(docPath, 'utf-8').replace(/\r\n/g, '\n');
👍 👍

2022-12-07 19:55 UTC, dustinbyrne approved these changes
Looks great.

2022-12-09 21:56 UTC, merged

2022-12-13 20:16 UTC, appland-release commented
:tada: This PR is included in version 0.56.0 :tada:

The release is available on:
- `v0.56.0`
- [GitHub release](https://github.com/getappmap/vscode-appland/releases/tag/v0.56.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: