Unpin end-user dependencies (scanner, CLI)
getappmap/vscode-appland pull request #527
Opened 2022-11-14 20:23 UTC by dustinbyrne

2022-11-15 18:44 UTC, dividedmind requested changes
Nice work with the locking! Do you think this could be the cause of the EBUSY errors on Windows during the installation? I don't know if people often run several vscode processes. (If you open a new window, is that a new process?)

Needs some small changes and then it should be good to go! (Once the build is green.)

2022-11-15 18:44 UTC, dividedmind commented on extern/yarn.js
> +*/
Well caught!

2022-11-15 18:44 UTC, dividedmind commented on src/services/nodeProcessService.ts
> +          await lockfile.check(this.globalStorageDir);
This returns true or false, you need to check the value.

2022-11-15 18:44 UTC, dividedmind commented on src/services/nodeProcessService.ts
> +      log.appendLine('Another process is currently installing dependencies. Waiting...');
Is it intended to use `appendLine` here and `append` in the other message? Neither of the messages contains a trailing newline.

2022-11-15 18:44 UTC, dividedmind commented on src/services/nodeProcessService.ts
> +      await lockfile.unlock(this.globalStorageDir);
You should probably use `release` instead, and only in the lock-acquired branch. With unlock you have a race – consider this sequence:
1. process alpha acquires the lockfile, starts installation,
2. beta sees the lock, waits around
3. alpha finishes, unlocks
4. beta notices the unlock and proceeds
5. gamma now acquires the lock and starts installation
6. beta reaches finally and releases the lock acquired by gamma
7. gamma is still installing despite no lock.

2022-11-15 18:52 UTC, dividedmind commented on src/services/nodeProcessService.ts
> +      await lockfile.lock(this.globalStorageDir);
BTW, you should probably hold onto the lock object. Otherwise it could get garbage collected and stop updating.

2022-11-17 16:09 UTC, dividedmind requested changes

2022-11-17 16:09 UTC, dividedmind commented on src/commands/generateOpenApi.ts
> +              log: openApiCmd.log.toString(),
Is `openApiCmd.log` an array? If so, it might be a good idea to do `join('')` instead of `toString()`. I've seen those ugly commas if some of our telemetry logs, I think they might come from here.

2022-11-18 17:06 UTC, dustinbyrne commented on src/commands/generateOpenApi.ts
> +              log: openApiCmd.log.toString(),
It's an array, but has a custom `toString` method which joins it together similar to what you've suggested.

2022-11-20 04:36 UTC, dividedmind approved these changes
Thanks, looks good now!

2022-11-21 16:12 UTC, merged

2022-11-29 16:22 UTC, appland-release commented
:tada: This PR is included in version 0.52.2 :tada:

The release is available on:
- `v0.52.2`
- [GitHub release](https://github.com/getappmap/vscode-appland/releases/tag/v0.52.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: