AppMap CLI and scanner specify `--appmap-dir` parameters
getappmap/vscode-appland pull request #532
Opened 2022-11-16 17:59 UTC by dustinbyrne

This is fully tested by automation.
- If `appmap_dir` is set within `appmap.yml` the processes will use it.
- If it's unset, `--appmap-dir .` will be used, effectively falling back to the project directory. 

These changes can be observed in the `Output` -> `AppMap: Services` log.

2022-11-16 18:43 UTC, symwell approved these changes
Looks good to me.

2022-11-16 18:43 UTC, symwell commented on test/integration/nodeProcesses/backgroundProcess.test.ts
> +            extensionPath: path.join(__dirname, '..', '..', '..', '..'),
Is this testing if the scanner might look out of the project directory and scan for more files than it should?

2022-11-16 19:18 UTC, kgilpin approved these changes

2022-11-16 19:21 UTC, kgilpin requested changes

2022-11-16 19:21 UTC, kgilpin commented on src/services/nodeProcessService.ts
> +    const appMapDir = (await lookupAppMapDir(folder.uri.fsPath)) || '.';
`mkdir -p` this directory before launching the process.

2022-11-16 23:07 UTC, kgilpin commented on src/services/nodeProcessService.ts
> +        Telemetry.sendEvent(DEBUG_EXCEPTION, {
In this case, use `.`

2022-11-16 23:08 UTC, kgilpin reviewed
If the AppMap dir is not createable, use `.`?

2022-11-16 23:11 UTC, kgilpin approved these changes

2022-11-16 23:12 UTC, kgilpin commented on src/services/nodeProcessService.ts
> +        Telemetry.sendEvent(DEBUG_EXCEPTION, {
Maybe not worth doing unless any other changes are also needed.

2022-11-17 01:52 UTC, merged

2022-11-17 14:19 UTC, appland-release commented
:tada: This PR is included in version 0.52.1 :tada:

The release is available on:
- `v0.52.1`
- [GitHub release](https://github.com/getappmap/vscode-appland/releases/tag/v0.52.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: