fix: Use best fit path when opening source of a code object
getappmap/vscode-appland pull request #619
Opened 2023-02-15 22:54 UTC by dustinbyrne

2023-02-23 00:28 UTC, ahtrotta requested changes
Looks good! Just a couple of comments/questions.

2023-02-23 00:28 UTC, ahtrotta commented on src/editor/appmapEditorProvider.ts
> +  private static readonly openWebviewPanels = new Map<string, vscode.WebviewPanel>();
With the addition of `openWebviewPanels`, can we get rid of `documents`? It seems like it's superfluous now. I think you'd just have to change the implementation of the `openDocuments` getter method.

2023-02-23 18:52 UTC, dustinbyrne commented on src/editor/appmapEditorProvider.ts
> +  private static readonly openWebviewPanels = new Map<string, vscode.WebviewPanel>();
AFAIK I cannot get the document from an instance of `WebviewPanel`. Unless you're suggesting the key be of type `AppMapDocument`, but that makes the interface difficult to use as the `AppMapDocument` class is coupled tightly with AppMap data.

2023-02-24 16:03 UTC, ahtrotta approved these changes

2023-03-01 15:07 UTC, merged

2023-03-01 16:11 UTC, appland-release commented
:tada: This PR is included in version 0.68.1 :tada:

The release is available on:
- `v0.68.1`
- [GitHub release](https://github.com/getappmap/vscode-appland/releases/tag/v0.68.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: