Add project root and repository to project:open telemetry
getappmap/vscode-appland pull request #630
Opened 2023-02-18 14:50 UTC by dividedmind

Fixes #629

2023-02-23 19:14 UTC, dustinbyrne requested changes
One small request regarding credentials in the git remote URL, but otherwise it's looking good!

2023-02-23 19:14 UTC, dustinbyrne commented on src/lib/git.ts
> +  return first.fetchUrl;
It's possible that `fetchUrl` contains basic auth credentials or access tokens in the URL. We should consider the following cases and strip out any potentially sensitive information:
```
https://$ACCESS_TOKEN@github.com/$ORG/$REPO
https://$USER:$PASSWORD@github.com/$ORG/$REPO
```

2023-02-23 19:14 UTC, dividedmind commented on src/lib/git.ts
> +  return first.fetchUrl;
Great point!

2023-03-01 20:46 UTC, dustinbyrne approved these changes

2023-03-01 22:34 UTC, dustinbyrne commented
I rebased this before merging but [this test](https://github.com/getappmap/vscode-appland/blob/master/test/integration/authentication/appmapServerLogin.test.ts#L30) appears to be failing after the rebase with `master`.

2023-03-02 19:00 UTC, dividedmind commented
> I rebased this before merging but [this test](https://github.com/getappmap/vscode-appland/blob/master/test/integration/authentication/appmapServerLogin.test.ts#L30) appears to be failing after the rebase with `master`.

The failure appears to be unrelated, but I fixed it anyway.

2023-03-02 19:26 UTC, merged

2023-03-03 18:00 UTC, appland-release commented
:tada: This PR is included in version 0.69.0 :tada:

The release is available on:
- `v0.69.0`
- [GitHub release](https://github.com/getappmap/vscode-appland/releases/tag/v0.69.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: