fix: reduce scanning for appmap.yml
getappmap/vscode-appland pull request #638
Opened 2023-02-27 15:17 UTC by apotterri

Reduce the cases where the extension scans the entire subtree under the current project directory.

Fixes #633 .

2023-02-28 14:18 UTC, dividedmind requested changes
There is some type weirdness happening there.

Also, I wonder if it wouldn't be a better design to move this logic into the `ConfigFileProvider` instead of littering the watchers with yet another parameter? Feels like it belongs there.

2023-02-28 14:18 UTC, dividedmind commented on src/services/nodeProcessService.ts
> +    const excludes = vscode.workspace.getConfiguration('files').get('watcherExclude') as string[];
Is it really a `string[]`? You seem to be using it with `Object.keys` later, which would give consecutive integers if that was the case.

2023-02-28 14:48 UTC, apotterri commented
> There is some type weirdness happening there.
> 
> Also, I wonder if it wouldn't be a better design to move this logic into the `ConfigFileProvider` instead of littering the watchers with yet another parameter? Feels like it belongs there.

I didn't put it in `ConfigFileProvider`, because `ConfigFileProvider` is so simple:
```
export type ConfigFileProvider = () => Promise<vscode.Uri[]>;
```
It seems reasonable to expand it with this functionality, though. Let me try it and see what it looks like.

2023-02-28 15:17 UTC, dividedmind commented
> > There is some type weirdness happening there.
> > Also, I wonder if it wouldn't be a better design to move this logic into the `ConfigFileProvider` instead of littering the watchers with yet another parameter? Feels like it belongs there.
> 
> I didn't put it in `ConfigFileProvider`, because `ConfigFileProvider` is so simple:
> 
> ```
> export type ConfigFileProvider = () => Promise<vscode.Uri[]>;
> ```
> 
> It seems reasonable to expand it with this functionality, though. Let me try it and see what it looks like.

Thanks! You can probably keep the simple API (at least consumer-side), just put more logic there :)

2023-03-01 15:04 UTC, dividedmind approved these changes

2023-03-01 15:52 UTC, merged

2023-03-01 16:11 UTC, appland-release commented
:tada: This PR is included in version 0.68.1 :tada:

The release is available on:
- `v0.68.1`
- [GitHub release](https://github.com/getappmap/vscode-appland/releases/tag/v0.68.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: