User can configure default appmap filter settings
getappmap/vscode-appland pull request #683
Opened 2023-05-10 22:23 UTC by ahtrotta

Fixes #681

2023-06-02 21:54 UTC, dustinbyrne requested changes
Looks good. I'd really only like to see `initializeDefaultFilter` return a `Promise` to avoid any future issues.

2023-06-02 21:54 UTC, dustinbyrne commented on src/editor/appmapEditorProvider.ts
> +    });
Nit - this should be a `forEach` as it's not transforming the value returned, just mutating it. Generally `map` shouldn't result in side effects.

2023-06-02 21:54 UTC, dustinbyrne commented on test/integration/savedFilters.test.ts
> +    ]);
I think this only passes because of the implementation of our mock `Momento` class:
https://github.com/getappmap/vscode-appland/blob/master/test/mocks/inMemoryMemento.ts#L12-L15

`initializeDefaultFilter` doesn't `await` the update or return a `Promise`. If it were actually hitting the disk I'd imagine this would fail.

2023-06-02 23:28 UTC, ahtrotta commented on src/editor/appmapEditorProvider.ts
> +    });
Good catch! I seem to have a bad habit of doing this :upside_down_face:

2023-06-02 23:29 UTC, ahtrotta commented on test/integration/savedFilters.test.ts
> +    ]);
Makes, sense, I changed it :+1:

2023-06-07 15:19 UTC, merged

2023-06-07 15:41 UTC, appland-release commented
:tada: This PR is included in version 0.84.0 :tada:

The release is available on:
- `v0.84.0`
- [GitHub release](https://github.com/getappmap/vscode-appland/releases/tag/v0.84.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: