feat: Organize runtime analysis
getappmap/vscode-appland pull request #738
Opened 2023-06-26 20:18 UTC by kgilpin

* Organize findings by date.
* Include failed tests in the findings view.
* Include inline commands to view AppMap as JSON, and delete an AppMap.

<img width="316" alt="Screen Shot 2023-06-26 at 4 33 06 PM" src="https://github.com/getappmap/vscode-appland/assets/86395/864d7135-94de-4a78-939a-a103f8463c79">

2023-06-26 20:22 UTC, kgilpin commented on src/extension.ts
> -import { FindingsTreeDataProvider } from './tree/findingsTreeDataProvider';
Moved to src/tree/index.ts

2023-06-26 20:23 UTC, kgilpin commented on src/services/findingsIndex.ts
>    private findingsBySourceUri = new Map<string, ResolvedFinding[]>();
This property is a `Map` but it's used like an `Object` throughout this class.

2023-06-26 20:24 UTC, kgilpin commented on test/fixtures/workspaces/project-several-findings/.gitignore
>  node_modules
The rest of the file changes are all tests.

2023-06-26 20:25 UTC, kgilpin commented on test/fixtures/workspaces/project-several-findings/app/controllers/users_controller.rb
> +class UsersController < ApplicationController
These fixture source files need to be exist in order for the finding problem location to resolve.

2023-06-26 20:26 UTC, kgilpin commented on test/fixtures/workspaces/project-several-findings/appmap.yml
> +name: project-several-findings
Instead of having static fixture findings, this project is now actually scanned.

2023-06-26 20:27 UTC, kgilpin commented on test/integration/analysisTree/enumerateTree.ts
> +import * as vscode from 'vscode';
The runtime analysis test will basically assert that the state of the entire tree matches an expectation, which is loaded from a JSON file. All that's tested is the labels, but that's enough to verify that it's working as expected.

2023-06-27 16:00 UTC, dustinbyrne commented on src/lib/deleteAppMap.ts
> +  await retry(async () => rm(indexDir, { force: true, recursive: true }));
We shouldn't remove the index directory here because it's likely that we'll miss `FileWatcher` events for files contained within. This is a limitation of VSCode's API (https://github.com/microsoft/vscode/issues/60813). There's now a separate service responsible for removing index directories once the contents have been ACK'd as deleted ([`IndexJanitor`](https://github.com/getappmap/vscode-appland/blob/49b8eb16964422110eafc8ce92d73d687a7801f3/src/lib/indexJanitor.ts#L20)).

2023-06-27 16:23 UTC, dustinbyrne commented on src/tree/findingsTreeDataProvider.ts
> +    const projects = vscode.workspace.workspaceFolders || [];
Nit - you shouldn't need to coerce this into an array because `undefined` has already been ruled out above

2023-06-27 16:25 UTC, dustinbyrne commented on src/tree/findingsTreeDataProvider.ts
> +      ?.findings()
Similarly the optional chain isn't necessary because `this.findingsIndex` is guaranteed to be defined. Normally the optional chain would cause the resulting type to optionally be `undefined` but in this case it looks like TypeScript is smart enough to recognize it'll always be defined.

2023-06-27 16:38 UTC, dustinbyrne requested changes
Looks great! The only necessary change from my perspective is to retain the index directory (https://github.com/getappmap/vscode-appland/pull/738#discussion_r1243994316). Other than that, it seems ready to go out.

2023-06-28 13:46 UTC, kgilpin commented on src/lib/deleteAppMap.ts
> +  await retry(async () => rm(indexDir, { force: true, recursive: true }));
OK. I was getting a test error related to the presence, or absence (I forget which) of this directory. I'll remove this line and if I see that error again I will send it over to you :-) I'm 99% sure it was unrelated to the changes in this PR.

2023-06-28 18:55 UTC, dustinbyrne approved these changes

2023-06-28 18:55 UTC, merged

2023-06-28 19:17 UTC, appland-release commented
:tada: This PR is included in version 0.91.0 :tada:

The release is available on:
- `v0.91.0`
- [GitHub release](https://github.com/getappmap/vscode-appland/releases/tag/v0.91.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: