Open appmap sign-in on installation
getappmap/vscode-appland pull request #743
Opened 2023-06-29 17:15 UTC by ahtrotta

Fixes #742 

This change makes it so that the appmap sidebar is opened to the sign-in page when the extension is installed.

2023-06-29 20:43 UTC, dustinbyrne requested changes

2023-06-29 20:43 UTC, dustinbyrne commented on src/extension.ts
> +
This will open up for anyone who isn't signed in. Can we limit it to new installs?

2023-06-29 20:53 UTC, ahtrotta commented on src/extension.ts
> +
Sure! I'll change it.

2023-06-30 16:09 UTC, dustinbyrne approved these changes

2023-06-30 16:10 UTC, merged

2023-06-30 16:41 UTC, appland-release commented
:tada: This PR is included in version 0.93.0 :tada:

The release is available on:
- `v0.93.0`
- [GitHub release](https://github.com/getappmap/vscode-appland/releases/tag/v0.93.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: