feat: Display *.diff.sequence.json files
getappmap/vscode-appland pull request #794
Opened 2023-09-05 17:10 UTC by kgilpin

2023-09-07 22:07 UTC, dustinbyrne requested changes

2023-09-07 22:07 UTC, dustinbyrne commented on src/editor/appmapEditorProvider.ts
> +        );
This violates the `CustomReadonlyEditorProvider` interface. What happens when `undefined` is returned? It'd be better to raise an exception otherwise this may result in unexpected behavior in the future.

2023-09-09 16:15 UTC, kgilpin commented
Tests passed on GitHub Actions.

2023-09-09 16:15 UTC, merged

2023-09-20 20:25 UTC, appland-release commented
:tada: This PR is included in version 0.101.0 :tada:

The release is available on:
- `v0.101.0`
- [GitHub release](https://github.com/getappmap/vscode-appland/releases/tag/v0.101.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: