fix: Drop the AppMap pin feature from VSCode
getappmap/vscode-appland pull request #803
Opened 2023-09-11 11:26 UTC by zermelo-wisen

Fixes #430 
 
Before
<img width="469" alt="Pasted Graphic 9" src="https://github.com/getappmap/vscode-appland/assets/98758224/001e9660-9259-4b79-b466-dbbb86311502">

After
<img width="476" alt="Pasted Graphic 8" src="https://github.com/getappmap/vscode-appland/assets/98758224/742bdfac-6979-40c8-a919-8832a5b685a9">

I wasn't able to run integration tests (I followed DEVELOPMENT.md) to see if there are related tests which need to be dropped, too. I was able to run other tests: unit, web-client, system.

`yarn run test:integration`

This creates an extensions.json file in the project root folder with the content like: `[{"identifier":{"id":"undefined_publisher.undefined"},...` and errors with: _Error while installing extensions: Invalid extensions content in vscode-userdata:/Users/z/Dev/vscode-appland/extensions.json_

2023-09-11 13:35 UTC, zermelo-wisen commented
@kgilpin, thank you. By the way I figured out that we need to run `pretest` script before running integration tests. Is this correct? The problem was that `yarn run compile` did not create out/test folder for tests. After I run `pretest` I was able to run the integration tests.

2023-09-12 15:52 UTC, kgilpin requested changes
I've realized that another change is needed. When the user clicks on a package, class or function in the Code Objects tree, we now need to prompt the user to open an AppMap. This is the same behavior that currently occurs when opening an HTTP server request or SQL query in the Code Objects tree.

Clicking a class or function currently opens the source file, and then the user can use the map pin to get to the AppMap. But now the map pin is gone.


<img width="244" alt="Screen Shot 2023-09-12 at 11 50 00 AM" src="https://github.com/getappmap/vscode-appland/assets/86395/c14d45d7-cdef-4c89-93c4-8f5789ebb787">

2023-09-13 17:15 UTC, kgilpin commented on src/tree/classMapTreeDataProvider.ts
> +    if (InspectableTypes.includes(codeObject.type) && codeObject.children.length === 0) {
Inspectable types includes packages and classes - https://github.com/getappmap/vscode-appland/blob/2918b276d4ee7045502841cca39c319c5eeae8e6/src/lib/CodeObjectEntry.ts#L22

So in the case of packages and classes, it's desirable to call `openCodeObjectInAppMap` even if the node has children. So please enable it for packages and classes. Add a new constant / enum to indicate which inspectable types should only be opened if they have 0 children.

2023-09-13 17:59 UTC, zermelo-wisen commented on src/tree/classMapTreeDataProvider.ts
> +    if (InspectableTypes.includes(codeObject.type) && codeObject.children.length === 0) {
If I understand correctly,

Applicable nodes = {All PACKAGE and CLASS nodes} U {Nodes of all other inspectable types with no children}

Is this correct?

2023-09-13 18:38 UTC, kgilpin commented
Yes, that's it.

2023-09-13 18:38 UTC, kgilpin commented on src/tree/classMapTreeDataProvider.ts
> +    if (InspectableTypes.includes(codeObject.type) && codeObject.children.length === 0) {
That’s right

2023-09-13 20:02 UTC, zermelo-wisen commented on src/tree/classMapTreeDataProvider.ts
> +    if (InspectableTypes.includes(codeObject.type) && codeObject.children.length === 0) {
Done.

2023-09-14 23:09 UTC, brikelly commented
@zermelo-wisen this is still a draft PR, but it sounds like it is ready to move ahead, correct?

2023-09-15 07:31 UTC, zermelo-wisen commented
Yes, I committed my last change.

2023-09-15 14:24 UTC, brikelly commented
OK @zermelo-wisen can you please change it to "Ready for review" and I'll have another developer review it, thanks

2023-09-15 14:28 UTC, zermelo-wisen commented
Done

2023-09-15 15:06 UTC, dustinbyrne requested changes
Looking good. I left a couple of comments below. In particular, please take a look at the comment regarding the duplicate comparisons. Once that's resolved this PR looks ready to merge.

2023-09-15 18:13 UTC, zermelo-wisen commented on src/tree/classMapTreeDataProvider.ts
> +      codeObject.type === CodeObjectEntryRootType.PACKAGE ||
When you consider entire if statement it will be true for all CLASS and PACKAGE objects no matter if they have children. But it will be true for other inspectible types only if they don't have children.

2023-09-15 18:31 UTC, zermelo-wisen commented on test/integration/classMapTree/classMapTree.test.ts
> +      );
Initially I wrote it as a loop, asserting each node while traversing the tree depth-first for just one path. But somehow I got some strange behaviour when I ran the test, like getting no children in actual variable after line 91 if I didn't have an assert statement outside the loop. 

I guess it's something related to the dynamics of Mocha, waitFor, multiple tries, and asynchronous statements. I wasn't able to understand the problem in a reasonable amount of time. So I decided to write each line explicitly thinking that it won't be a problem in a test case.

I will take another look and try to DRY it a bit.

I'd be happy if you have an idea about what I could have missed in the problem above.

2023-09-15 18:50 UTC, zermelo-wisen commented on test/integration/classMapTree/classMapTree.test.ts
> +      );
I think I understand the problem now. I'm going to put another assertion before the loop in order to cause several retries and give chance to the UI to load `actual.children`.

2023-09-15 19:29 UTC, zermelo-wisen commented on test/integration/classMapTree/classMapTree.test.ts
> +      );
Thank you for pointing this out. It made me rethink about test behaviour and figure out the cause. 

I DRY'd it by converting it to a loop.

2023-09-15 20:42 UTC, moxw approved these changes
Looks good!

2023-09-15 22:12 UTC, merged

2023-09-20 20:25 UTC, appland-release commented
:tada: This PR is included in version 0.101.0 :tada:

The release is available on:
- `v0.101.0`
- [GitHub release](https://github.com/getappmap/vscode-appland/releases/tag/v0.101.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: