Prompt Java and Python to install AppMap
getappmap/vscode-appland pull request #804
Opened 2023-09-11 19:58 UTC by zermelo-wisen

Fixes #698

2023-09-15 14:11 UTC, ahtrotta requested changes
Looks good! Could you address the small changes I requested? Thanks!

2023-09-15 14:11 UTC, ahtrotta commented on test/integration/actions/promptInstall.test.ts
> -      assert(!showInformationMessage.called);
I don't think we should remove this test that checks that the prompt is not shown. Can you add it back in and change it so that the language is `JavaScript` and the framework is `express.js`?

2023-09-15 14:11 UTC, ahtrotta commented on src/actions/promptInstall.ts
> +        project.metadata.webFramework?.name === 'Django')));
Could you make this more readable by using variables?
```
const language = project.metadata.language?.name;
const webFramework = project.metadata.webFramework?.name;
  
return ((language === 'Ruby' && webFramework === 'Rails') ||
(language === 'Java' && webFramework === 'Spring') ||
(language === 'Python' && (webFramework === 'flask' || webFramework === 'Django')));

2023-09-15 14:23 UTC, zermelo-wisen commented on src/actions/promptInstall.ts
> +        project.metadata.webFramework?.name === 'Django')));
Sure.

I thought about this, but later decided to go on like the original code.

How about this, is it even more clear?

```
const languageFramework = project.metadata.language?.name + "-" + project.metadata.webFramework?.name;
return ["Ruby-Rails", "Java-Spring", "Python-flask", "Python-Django"].contains(languageFramework);
```

I will do it your way unless you approve my new suggestion.

2023-09-15 14:26 UTC, ahtrotta commented on src/actions/promptInstall.ts
> +        project.metadata.webFramework?.name === 'Django')));
Sure, that way looks fine :+1:

2023-09-15 15:03 UTC, zermelo-wisen commented
Changes done.

2023-09-15 15:51 UTC, ahtrotta approved these changes

2023-09-15 15:52 UTC, merged

2023-09-20 20:25 UTC, appland-release commented
:tada: This PR is included in version 0.101.0 :tada:

The release is available on:
- `v0.101.0`
- [GitHub release](https://github.com/getappmap/vscode-appland/releases/tag/v0.101.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: