fix: Instructions page should be reactive to the Java agent file
getappmap/vscode-appland pull request #808
Opened 2023-09-13 08:27 UTC by zermelo-wisen

Fixes #764

2023-09-13 11:29 UTC, kgilpin commented on src/services/javaAssets.ts
> +    const wholePathWatcher = vscode.workspace.createFileSystemWatcher(
In my experience, any time we have a watcher we should also do a less frequent periodic scan of the directory (say every 10 seconds) - because watch events are unreliable especially for deletions. We want to make sure that our data is eventually consistent with the file system.

2023-09-13 11:30 UTC, kgilpin commented on src/services/javaAssets.ts
> +    );
Can we be more specific with the watch pattern? .appmap can eventually contain a lot of files. We are only interested for this purpose in the lib folder. Right?

2023-09-13 11:31 UTC, kgilpin commented on src/services/javaAssets.ts
> +    );
So what I’m saying is, constrain the pattern to the specific folders you care about because there may be other folders that contain many files.

2023-09-13 11:32 UTC, kgilpin commented on src/services/javaAssets.ts
> +    );
Or just periodically check if the file you care about exists. This will be more robust than a watcher and have negligible performance implications for the user. Watchers just aren’t reliable.

2023-09-13 11:46 UTC, zermelo-wisen commented on src/services/javaAssets.ts
> +    );
Thank you for pointing this out. Sorry, didn't know that there can be many files there. 

If I understand right (and based on my tests), to be specific, I need to create several watchers to cover each part of the path, since we want to make sure the exact path of `~/.appmap/lib/java/appmap.jar` is valid:

-watcher 1 `[~, .appmap]`
-watcher 2 `[.appmap, lib]`
-watcher 3 `[lib, java]`
-watcher 4 `[java, appmap.jar]`

If I omit, for example the first one, we can't react if the user deletes the `~/.appmap` folder.

I'm going to check to be sure if a single watcher like `[~/.appmap, lib/java/appmap.jar]` will do the job.

2023-09-13 11:56 UTC, zermelo-wisen commented on src/services/javaAssets.ts
> +    );
> Or just periodically check if the file you care about exists. This will be more robust than a watcher and have negligible performance implications for the user. Watchers just aren’t reliable.

Ok, I just read your comment above. I'm going to convert it to a periodic (2 seconds?) check.

2023-09-13 11:59 UTC, kgilpin commented on src/services/javaAssets.ts
> +    );
Ok just periodically list the directory `~/.appmap/lib/java` and that should tell you what you need to know. 2 seconds sounds good to me.

2023-09-13 12:26 UTC, zermelo-wisen commented on src/services/javaAssets.ts
> +    );
Done.

2023-09-18 15:28 UTC, dustinbyrne requested changes

2023-09-18 15:28 UTC, dustinbyrne commented on src/services/javaAssets.ts
> +    JavaAssets.status = exists ? AssetStatus.UpToDate : AssetStatus.Error;
Check out the definition of `installLatestJavaJar` above. If the status is `Updating`, we don't necessarily want to flag this as an error immediately; we have more information than that. Maybe it'd be best to exit early from the tick if we're in an `Updating` state.

2023-09-18 20:40 UTC, zermelo-wisen commented on src/services/javaAssets.ts
> +    JavaAssets.status = exists ? AssetStatus.UpToDate : AssetStatus.Error;
Done

2023-09-22 17:45 UTC, merged