feat: New users see a notification box when they create their first map
getappmap/vscode-appland pull request #823
Opened 2023-09-18 20:16 UTC by zermelo-wisen

Fixes #817.

2023-09-18 23:56 UTC, ahtrotta requested changes
This is cool! It's a little bit choppy, though. When I click the button, it first focuses on the `Code Objects` tree for a split second:

![image](https://github.com/getappmap/vscode-appland/assets/45714532/ba64a808-777a-4670-af1d-f31cb99e1b9d)

And then it focuses on the `AppMaps` tree, and it doesn't render all that well:

![image](https://github.com/getappmap/vscode-appland/assets/45714532/c5f7cf3e-58c4-403d-952c-ebe67df9161b)

Can you change it so that the `Code Objects` tree does not get focused before the `AppMaps` tree?

Also, can you see if you can make the `AppMaps` tree open so that it occupies ~50% of the side panel and the top of the tree is always visible? Like this:

![image](https://github.com/getappmap/vscode-appland/assets/45714532/11860e46-4ab2-4ada-9862-84359dcb8d1f)

It might not be possible, but it's worth looking into.

2023-09-18 23:56 UTC, ahtrotta commented on test/integration/lib/firstAppMapNotification.test.ts
> +    //appmapWatcher = new MockFileSystemWatcher();
Please delete this comment

2023-09-19 09:20 UTC, zermelo-wisen commented
I was able to prevent automatic focus on Code Objects. Now we focus directly on AppMaps tree.

However, I couldn't find a way to specify or cause a change in TreeView size. It seems that this is a related discussion: https://github.com/microsoft/vscode/issues/123715.

By the way, GitHub diff viewer in the Files changed tab here does not show the diffs well for the `installGuideWebView.ts` file. I guess it's because of the indentation change after introducing a new parameter which broke the line to make it "prettier". I suggest to check the diffs of this file inside VS Code.

2023-09-19 15:50 UTC, ahtrotta approved these changes
Great, thanks!

2023-09-19 15:50 UTC, merged

2023-09-20 20:24 UTC, appland-release commented
:tada: This PR is included in version 0.101.0 :tada:

The release is available on:
- `v0.101.0`
- [GitHub release](https://github.com/getappmap/vscode-appland/releases/tag/v0.101.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: